FROM golang:1.22.5-bullseye AS go-builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY .default.env ./cmd/config/.default.env

# Start both applications
ENTRYPOINT ["go", "test"]
